common:
  frame_id: "fgo_mot"
  use_imu: false
  lidar_input_topic: "/points_raw"
  imu_topic: "/imu_correct"
  horizon_scans: 2000
  line_num: 64
  corner_leaf_size: 0.2
  surf_leaf_size: 0.4
  data_set: "kitti"
  sequence: 0

  #extrinsic imu to lidar
  ql2b_w: 1
  ql2b_x: 0
  ql2b_y: 0
  ql2b_z: 0

  tl2b_x: 0
  tl2b_y: 0
  tl2b_z: 0

kitti_helper:
  base_path: "/media/great/I/dataset/tracking/training/"
  # sequences: [1, 6, 8, 10, 12, 13, 14, 15, 16, 18, 19]
  sequences: [0, 1, 2, 3, 4, 5,6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  # sequences: [8]
  # sequences: [0]
  data_pub_rate: 3
  useoxts: false
  OneFile: true
  detection_in_one_file: true
  to_bag: false
  out_bag_path: "/home/great/FGO-MOT-ws/output/"

image_projection:
  patchwork_config_file: "/home/great/FGO-MOT-ws/src/fgo-mot/config/patchwork_params.yaml"
  ang_res_x: 0.2
  ang_res_y: 0.427
  ang_bottom: 24.9
  sensorMinimumRange: 0.02
  groundScanInd: 25
  minBboxpointnum: 2  # >=1
  minBboxscore: -10000.0 #-10000
  # segmentation_strategy 0---->priori independent  1---->partially dependent on priori   2---->completely dependent on priori
  segmentation_strategy: 2

feature:
  edge_threshold: 500.0
  surf_threshold: 500.0
  k_correspondences: 10
  gicp_epsilon: 0.001

preprocessing:
  surf_thres: 0.28
  edge_thres: 4
  ds_rate: 0

lidar_odometry:
  max_num_iter: 5
  scan_match_cnt: 1
  ifDeskew: false

object_tracker:
  output_path: "/home/great/FGO-MOT-ws/output/"
  use_oxts: true
  maxBoxLossNum: 8 #8, 9
  birthmin: 4 #4
  max_costmatrixvalue: 1.5797 #0.7  0.85  # 1.5   1.58 best # 1.3 best  1.25   1.5797
  ZUPT_Linear_vel: 0.7
  ZUPT_Angular_vel: 0.03
  min_feature_point: 5 #20
  sliding_window_opt: true
  # motion model: 0--->null, 1--->cvrt, 2--->const_acc_w
  motion_model: 1
  use_ZUPT: true
  use_nhc: true
  use_point_feature: false
  use_ypr_model: false
  use_box_model: true
  use_smooth_frame_factor: false
  use_marginalization: false
  obj_local_map_size: 10
  voxel_leaf_size: 0.05
  min_corner_nums_kdtree: 20
  min_surf_nums_kdtree: 20
  smooth_thresh: 50
  output_predict: false
  trans_variance: true
  motion_weight: 50 # 50
  detection_weight: 100  # 100
  static_weight: 1